### ISSUE TITLE
請問能否從GOSDK中導出CSV?

### ISSUE THREAD

**Issue by x12901** [BernieTs/GocatorDataCsv2PCD#1]
謝謝,很棒的項目,我用我的模型成功復現了項目.有一個小問題我不知道是否SDK也能導出CSV?

**Comment by BernieTs** [comment]
我這邊沒有使用過GoSDK進行CSV導出，不過在GoSDK的GoSensor Class底下有個GoSensor_ExportCsv function可以嘗試看看。
`
kStatus  GoSensor_ExportCsv (GoSensor sensor, const kChar *dstFileName)
`

**Comment by x12901** [comment]
非常感谢
